### PR TITLE
Add locale support

### PR DESCRIPTION
**Pull request by mlang38**
Add the ability to install localized versions of Wordpress

### CODE REVIEW

**Comment by mlang38** [comment]
We could also install and activate locales via `wp-cli core language install/activate [locale]`.
`wp-cli core download --locale` also creates first page and post, bloginfo etc... whereas `wp-cli core language activate` only sets WPLANG option for internationalized strings in core, themes and plugins.

**Comment by tersmitten** [comment]
Looks great. I'll try to merge this soon.

> We could also install and activate locales via `wp-cli core language install/activate [locale]`.

Maybe you could add that in another pull request?

**Comment by mlang38** [comment]
Perhaps in a few days, no time now. It is not a feature as important as the 'locale' one.

**Comment by tersmitten** [comment]
No problem

**Pull request merged**
